"""
Streamlit front end.

    streamlit run streamlit_app.py

Layout: a chat column on the left, a live KPI rail on the right. Each answer
renders as Insight -> Chart -> Data -> SQL -> Trace, which is deliberately the
order a stakeholder reads in (conclusion first, evidence on demand).
"""

from __future__ import annotations

import pandas as pd
import streamlit as st

from app import charts
from app.pipeline import EXAMPLE_QUESTIONS, Analyst

st.set_page_config(page_title="AI Business Analyst",
                   page_icon="📊", layout="wide")

CSS = """
<style>
  .block-container {padding-top: 2rem; max-width: 1400px;}
  .stChatMessage {background: transparent;}
  .kpi {border:1px solid rgba(128,128,128,.25); border-radius:12px;
        padding:14px 16px; margin-bottom:10px;}
  .kpi .label {font-size:.78rem; text-transform:uppercase;
               letter-spacing:.06em; opacity:.65;}
  .kpi .value {font-size:1.55rem; font-weight:650; line-height:1.25;}
  .kpi .delta-up {color:#2a9d8f; font-size:.85rem;}
  .kpi .delta-down {color:#d1495b; font-size:.85rem;}
  .pill {display:inline-block; padding:2px 9px; border-radius:999px;
         font-size:.72rem; border:1px solid rgba(128,128,128,.35);
         margin-right:6px; opacity:.85;}
</style>
"""
st.markdown(CSS, unsafe_allow_html=True)


# --------------------------------------------------------------------------- #
@st.cache_resource(show_spinner=False)
def get_analyst() -> Analyst:
    return Analyst()


@st.cache_data(show_spinner=False)
def kpis(_analyst: Analyst) -> dict:
    db = _analyst.db
    monthly = db.run(
        "SELECT substr(order_date,1,7) AS m, ROUND(SUM(revenue),2) AS revenue, "
        "ROUND(SUM(profit),2) AS profit, COUNT(DISTINCT order_id) AS orders "
        "FROM v_sales GROUP BY 1 ORDER BY 1"
    ).dataframe
    last, prev = monthly.iloc[-1], monthly.iloc[-2]
    return {
        "monthly": monthly,
        "month": last["m"],
        "revenue": last["revenue"],
        "revenue_delta": (last["revenue"] - prev["revenue"]) / prev["revenue"] * 100,
        "orders": int(last["orders"]),
        "orders_delta": (last["orders"] - prev["orders"]) / prev["orders"] * 100,
        "margin": last["profit"] / last["revenue"] * 100,
        "aov": last["revenue"] / last["orders"],
    }


def kpi_card(label: str, value: str, delta: float | None = None) -> str:
    d = ""
    if delta is not None:
        cls = "delta-up" if delta >= 0 else "delta-down"
        d = f"<div class='{cls}'>{delta:+.1f}% vs prior month</div>"
    return (f"<div class='kpi'><div class='label'>{label}</div>"
            f"<div class='value'>{value}</div>{d}</div>")


def render_chart(spec) -> None:
    if spec.kind == "table" or spec.data.empty:
        if not spec.data.empty:
            st.dataframe(spec.data, use_container_width=True, hide_index=True)
        return
    if spec.kind == "metric":
        st.metric(spec.title or spec.y, f"{spec.data[spec.y].iloc[0]:,.2f}")
        return
    fig = charts.to_plotly(spec)
    if fig is not None:
        st.plotly_chart(fig, use_container_width=True)


def render_answer(ans) -> None:
    st.markdown(ans.insight)

    if ans.chart.data is not None and not ans.chart.data.empty:
        render_chart(ans.chart)

    for extra in ans.extra_charts:
        with st.expander(extra.title or "More detail", expanded=False):
            render_chart(extra)

    tabs = st.tabs(["Data", "SQL", "How I got here"])
    with tabs[0]:
        if ans.data.empty:
            st.caption("No rows.")
        else:
            st.dataframe(ans.data, use_container_width=True, hide_index=True)
            st.download_button(
                "Download CSV", ans.data.to_csv(index=False).encode(),
                file_name="analysis.csv", mime="text/csv",
                key=f"dl-{abs(hash(ans.question))}-{len(ans.data)}",
            )
    with tabs[1]:
        st.code(ans.sql, language="sql")
        st.caption(f"Generated by: **{ans.sql_source}**")
    with tabs[2]:
        st.markdown(
            f"<span class='pill'>{ans.plan.intent}</span>"
            f"<span class='pill'>{ans.plan.metric}</span>"
            f"<span class='pill'>{ans.elapsed_s:.2f}s</span>",
            unsafe_allow_html=True)
        for step in ans.trace:
            st.text(f"• {step}")
        if ans.facts:
            st.caption("Facts passed to the writer:")
            st.text(ans.facts)


# --------------------------------------------------------------------------- #
try:
    analyst = get_analyst()
except FileNotFoundError as exc:
    st.error(str(exc))
    st.info("Run `python data/generate_data.py` first, then reload this page.")
    st.stop()

with st.sidebar:
    st.header("AI Business Analyst")
    st.caption("Ask a business question in plain English. The assistant writes "
               "the SQL, runs it, analyses the result and explains it.")
    st.divider()
    st.markdown(f"**LLM:** `{analyst.llm.provider}` · `{analyst.llm.model}`")
    if analyst.llm.is_offline:
        st.info("Running in offline mode — SQL and insights come from the "
                "built-in rule engine. Set `ANTHROPIC_API_KEY` or "
                "`OPENAI_API_KEY` in `.env` for LLM-written answers.")
        with st.expander("Why offline?"):
            for reason in analyst.llm.reasons:
                st.text(f"• {reason}")
            st.caption("Run `python check_llm.py` for a full diagnosis.")
    st.markdown(f"**Data:** {analyst.data_start} → {analyst.data_end}")
    st.divider()
    st.markdown("**Try asking**")
    for q in EXAMPLE_QUESTIONS:
        if st.button(q, use_container_width=True, key=f"ex-{q}"):
            st.session_state.pending = q
    st.divider()
    if st.button("Clear conversation", use_container_width=True):
        st.session_state.history = []
        st.rerun()

left, right = st.columns([2.1, 1], gap="large")

with right:
    k = kpis(analyst)
    st.markdown(f"#### Snapshot · {k['month']}")
    st.markdown(kpi_card("Revenue", f"{k['revenue']:,.0f}", k["revenue_delta"]),
                unsafe_allow_html=True)
    st.markdown(kpi_card("Orders", f"{k['orders']:,}", k["orders_delta"]),
                unsafe_allow_html=True)
    st.markdown(kpi_card("Gross margin", f"{k['margin']:.1f}%"),
                unsafe_allow_html=True)
    st.markdown(kpi_card("Avg order value", f"{k['aov']:,.0f}"),
                unsafe_allow_html=True)
    spark = charts.ChartSpec(kind="line", title="Revenue by month",
                             x="m", y="revenue", data=k["monthly"])
    render_chart(spark)

with left:
    st.session_state.setdefault("history", [])
    st.session_state.setdefault("pending", None)

    for item in st.session_state.history:
        with st.chat_message("user"):
            st.write(item["question"])
        with st.chat_message("assistant"):
            render_answer(item["answer"])

    typed = st.chat_input("e.g. Why did revenue drop in March?")
    question = typed or st.session_state.pending
    st.session_state.pending = None

    if question:
        with st.chat_message("user"):
            st.write(question)
        with st.chat_message("assistant"):
            with st.spinner("Thinking, querying, analysing…"):
                ans = analyst.ask(question)
            render_answer(ans)
        st.session_state.history.append({"question": question, "answer": ans})
